# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ca34818e6cf09832e39842ed124345b6c323edb7b1885dc248c9295a4fb7c8fb46dc91576658d7c71ce17b3ddd9c7e69bf7e298b309ad7d98ad952973f9e74a9

test:
  secret_key_base: a778cbbdbfd969b81ddf8f32ad6e2fd11c2212e70c0f8f355749259c1f84bde63e998ef15eb0a48580744ba6dac952548398d75ed5fe3dd03342e3cdbc05063f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
